=== Conanjun/HK_CPDT/www/WEB-INF/config/organization/record_id.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:simpleType name="methodType">
		<xsd:restriction base="xsd:NMTOKEN">
			<xsd:enumeration value="AUTO"/>
			<xsd:enumeration value="MANUAL"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="prefixType">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="5"/>
			<xsd:pattern value="[\-A-Za-z0-9_]*"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:group name="mainIdElement">
		<xsd:sequence>
			<xsd:element name="creation_method" type="methodType"/>
			<xsd:element name="id_prefix" type="prefixType"/>
		</xsd:sequence>
	</xsd:group>
	<xsd:element name="record_id">
		<xsd:complexType>
			<xsd:all>
				<xsd:element name="learning_solution_id">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:group ref="mainIdElement"/>
							<xsd:element name="class_id_prefix" type="prefixType"/>
							<xsd:element name="session_id_prefix" type="prefixType"/>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="user_group_id">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:group ref="mainIdElement"/>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
			</xsd:all>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== Conanjun/HK_CPDT/www/WEB-INF/config/organization/cw/record_id.xml
<?xml version="1.0" encoding="UTF-8"?>
<record_id xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="..\record_id.xsd">
	<learning_solution_id>
		<creation_method>AUTO</creation_method>
		<id_prefix>WBLS</id_prefix>
		<class_id_prefix>WBCS</class_id_prefix>
		<session_id_prefix>WBSN</session_id_prefix>
	</learning_solution_id>
	<user_group_id>
		<creation_method>MANUAL</creation_method>
		<id_prefix>WBUG</id_prefix>
	</user_group_id>
</record_id>
