=== Conanjun/HK_CPDT/www/WEB-INF/config/organization/user_management.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="http://www.w3.org/2001/03/xml.xsd"/>
	<xsd:simpleType name="nonNullStringType">
		<xsd:restriction base="xsd:string">
			<xsd:minLength value="1"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="posIntType">
		<xsd:restriction base="xsd:int">
			<xsd:minInclusive value="1"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="userIdLengthType">
		<xsd:restriction base="posIntType">
			<xsd:maxInclusive value="20"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="userPasswordLengthType">
		<xsd:restriction base="posIntType">
			<xsd:maxInclusive value="20"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:complexType name="labelType">
		<xsd:simpleContent>
			<xsd:extension base="xsd:string">
				<xsd:attribute ref="xml:lang" use="required"/>
			</xsd:extension>
		</xsd:simpleContent>
	</xsd:complexType>
	<xsd:complexType name="optionType">
		<xsd:sequence>
			<xsd:element name="label" type="labelType" maxOccurs="unbounded"/>
		</xsd:sequence>
		<xsd:attribute name="id" type="nonNullStringType" use="required"/>
		<xsd:attribute name="default" type="xsd:boolean" use="optional" default="false"/>
	</xsd:complexType>
	<xsd:complexType name="optionListType">
		<xsd:sequence>
			<xsd:element name="option" type="optionType" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="userExtAttributeType">
		<xsd:sequence>
			<xsd:element name="label" type="labelType" maxOccurs="unbounded"/>
			<xsd:element name="option_list" type="optionListType" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
		<xsd:attribute name="readonly" type="readonlyType" use="optional" default="false"/>
		<xsd:attribute name="searchable" type="searchableType" use="optional" default="none"/>
		<xsd:attribute name="showempty" type="xsd:boolean" use="optional" default="false"/>
		<xsd:attribute name="active" type="xsd:boolean" use="required"/>
		<xsd:attribute name="instr_attr" type="xsd:boolean" use="optional" default="false"/>
		<xsd:attribute name="type" type="type" use="optional"/>
		<xsd:attribute name="value" type="xsd:string" use="optional" default="none"/>
		<xsd:attribute name="public_ind" type="xsd:boolean" use="optional" default="false"/>
		<xsd:attribute name="group" type="xsd:string"/>
		<xsd:attribute name="publicity" type="xsd:int"/>
		<xsd:attribute name="fieldname" type="xsd:string"/>
		<xsd:attribute name="registration" type="xsd:boolean" use="optional" default="false"/>
		<xsd:attribute name="allowEmpty" type="xsd:boolean" use="optional" default="true"/>
		<xsd:attribute name="dbMaxLength" type="xsd:int" use="optional"/>
		<xsd:attribute name="dbMinLength" type="xsd:int" use="optional"/>
	</xsd:complexType>
	<xsd:complexType name="userAttributeType">
		<xsd:sequence>
			<xsd:element name="label" type="labelType" maxOccurs="unbounded"/>
			<xsd:element name="option_list" type="optionListType" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
		<xsd:attribute name="readonly" type="readonlyType" use="optional" default="false"/>
		<xsd:attribute name="searchable" type="searchableType" use="optional" default="none"/>
		<xsd:attribute name="showempty" type="xsd:boolean" use="optional" default="false"/>
		<xsd:attribute name="hidden" type="xsd:boolean" use="optional" default="false"/>
		<xsd:attribute name="instr_attr" type="xsd:boolean" use="optional" default="false"/>
		<xsd:attribute name="type" type="type" use="optional"/>
		<xsd:attribute name="value" type="xsd:string" use="optional" default="none"/>
		<xsd:attribute name="public_ind" type="xsd:boolean" use="optional" default="false"/>
		<xsd:attribute name="group" type="xsd:string"/>
		<xsd:attribute name="publicity" type="xsd:int"/>
		<xsd:attribute name="fieldname" type="xsd:string"/>
		<xsd:attribute name="registration" type="xsd:boolean" use="optional" default="false"/>
		<xsd:attribute name="allowEmpty" type="xsd:boolean" use="optional" default="true"/>
		<xsd:attribute name="dbMaxLength" type="xsd:int" use="optional"/>
		<xsd:attribute name="dbMinLength" type="xsd:int" use="optional"/>
		<xsd:attribute name="groupLevel" type="xsd:int" use="optional" default="0"/>
		<xsd:attribute name="gradeLevel" type="xsd:int" use="optional" default="0"/>
	</xsd:complexType>
	<xsd:simpleType name="readonlyType">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="all"/>
			<xsd:enumeration value="true"/>
			<xsd:enumeration value="false"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="type">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="text"/>
			<xsd:enumeration value="date"/>
			<xsd:enumeration value="comboBox"/>
			<xsd:enumeration value="checkBox"/>
			<xsd:enumeration value="textarea"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="searchableType">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="adv"/>
			<xsd:enumeration value="all"/>
			<xsd:enumeration value="none"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:complexType name="userIdType">
		<xsd:sequence>
			<xsd:element name="label" type="labelType" maxOccurs="unbounded"/>
		</xsd:sequence>
		<xsd:attribute name="readonly" type="readonlyType" use="optional" default="false"/>
		<xsd:attribute name="searchable" type="searchableType" use="optional" default="none"/>
		<xsd:attribute name="showempty" type="xsd:boolean" use="optional" default="false"/>
		<xsd:attribute name="hidden" type="xsd:boolean" use="optional" default="false"/>
		<xsd:attribute name="min_length" type="userIdLengthType" use="required"/>
		<xsd:attribute name="max_length" type="userIdLengthType" use="required"/>
		<xsd:attribute name="instr_attr" type="xsd:boolean" use="optional" default="false"/>
		<xsd:attribute name="type" type="type" use="optional"/>
		<xsd:attribute name="value" type="xsd:string" use="optional" default="none"/>
		<xsd:attribute name="public_ind" type="xsd:boolean" use="optional" default="false"/>
		<xsd:attribute name="group" type="xsd:string"/>
		<xsd:attribute name="publicity" type="xsd:int"/>
		<xsd:attribute name="fieldname" type="xsd:string"/>
		<xsd:attribute name="registration" type="xsd:boolean" use="optional" default="false"/>
		<xsd:attribute name="allowEmpty" type="xsd:boolean" use="optional" default="true"/>
	</xsd:complexType>
	<xsd:complexType name="userPasswordType">
		<xsd:sequence>
			<xsd:element name="label" type="labelType" maxOccurs="unbounded"/>
		</xsd:sequence>
		<xsd:attribute name="readonly" type="xsd:boolean" use="optional" default="false"/>
		<xsd:attribute name="searchable" type="searchableType" use="optional" default="none"/>
		<xsd:attribute name="showempty" type="xsd:boolean" use="optional" default="false"/>
		<xsd:attribute name="hidden" type="xsd:boolean" use="optional" default="false"/>
		<xsd:attribute name="min_length" type="userPasswordLengthType" use="required"/>
		<xsd:attribute name="max_length" type="userPasswordLengthType" use="required"/>
		<xsd:attribute name="type" type="type" use="optional"/>
		<xsd:attribute name="group" type="xsd:string"/>
		<xsd:attribute name="publicity" type="xsd:int"/>
		<xsd:attribute name="registration" type="xsd:boolean" use="optional" default="false"/>
		<xsd:attribute name="fieldname" type="xsd:string"/>
		<xsd:attribute name="allowEmpty" type="xsd:boolean" use="optional" default="true"/>
	</xsd:complexType>
	<xsd:complexType name="profileAttributesType">
		<xsd:sequence>
			<xsd:element name="user_id" type="userIdType"/>
			<xsd:element name="password" type="userPasswordType"/>
			<xsd:element name="name" type="userAttributeType"/>
			<xsd:element name="nickname" type="userAttributeType"/>
			<xsd:element name="gender" type="userAttributeType"/>
			<xsd:element name="date_of_birth" type="userAttributeType"/>
			<xsd:element name="email" type="userAttributeType"/>
			<xsd:element name="phone" type="userAttributeType"/>
			<xsd:element name="fax" type="userAttributeType"/>
			<xsd:element name="extension_41" type="userExtAttributeType"/>
			<xsd:element name="extension_42" type="userExtAttributeType"/>
			<xsd:element name="job_title" type="userAttributeType"/>
			<xsd:element name="join_date" type="userAttributeType"/>
			<xsd:element name="source" type="userAttributeType"/>
			<xsd:element name="extension_1" type="userExtAttributeType"/>
			<xsd:element name="extension_2" type="userExtAttributeType"/>
			<xsd:element name="extension_3" type="userExtAttributeType"/>
			<xsd:element name="extension_4" type="userExtAttributeType"/>
			<xsd:element name="extension_5" type="userExtAttributeType"/>
			<xsd:element name="extension_6" type="userExtAttributeType"/>
			<xsd:element name="extension_7" type="userExtAttributeType"/>
			<xsd:element name="extension_8" type="userExtAttributeType"/>
			<xsd:element name="extension_9" type="userExtAttributeType"/>
			<xsd:element name="extension_10" type="userExtAttributeType"/>
			<xsd:element name="extension_11" type="userExtAttributeType"/>
			<xsd:element name="extension_12" type="userExtAttributeType"/>
			<xsd:element name="extension_13" type="userExtAttributeType"/>
			<xsd:element name="extension_14" type="userExtAttributeType"/>
			<xsd:element name="extension_15" type="userExtAttributeType"/>
			<xsd:element name="extension_16" type="userExtAttributeType"/>
			<xsd:element name="extension_17" type="userExtAttributeType"/>
			<xsd:element name="extension_18" type="userExtAttributeType"/>
			<xsd:element name="extension_19" type="userExtAttributeType"/>
			<xsd:element name="extension_20" type="userExtAttributeType"/>
			<xsd:element name="extension_21" type="userExtAttributeType"/>
			<xsd:element name="extension_22" type="userExtAttributeType"/>
			<xsd:element name="extension_23" type="userExtAttributeType"/>
			<xsd:element name="extension_24" type="userExtAttributeType"/>
			<xsd:element name="extension_25" type="userExtAttributeType"/>
			<xsd:element name="extension_26" type="userExtAttributeType"/>
			<xsd:element name="extension_27" type="userExtAttributeType"/>
			<xsd:element name="extension_28" type="userExtAttributeType"/>
			<xsd:element name="extension_29" type="userExtAttributeType"/>
			<xsd:element name="extension_30" type="userExtAttributeType"/>
			<xsd:element name="extension_31" type="userExtAttributeType"/>
			<xsd:element name="extension_32" type="userExtAttributeType"/>
			<xsd:element name="extension_33" type="userExtAttributeType"/>
			<xsd:element name="extension_34" type="userExtAttributeType"/>
			<xsd:element name="extension_35" type="userExtAttributeType"/>
			<xsd:element name="extension_36" type="userExtAttributeType"/>
			<xsd:element name="extension_37" type="userExtAttributeType"/>
			<xsd:element name="extension_38" type="userExtAttributeType"/>
			<xsd:element name="extension_39" type="userExtAttributeType"/>
			<xsd:element name="extension_40" type="userExtAttributeType"/>
			<xsd:element name="extension_43" type="userExtAttributeType"/>
			<xsd:element name="extension_44" type="userExtAttributeType"/>
			<xsd:element name="extension_45" type="userExtAttributeType"/>
			<xsd:element name="group" type="userAttributeType"/>
			<xsd:element name="grade" type="userAttributeType"/>
			<xsd:element name="competency" type="userAttributeType"/>
			<xsd:element name="role" type="userAttributeType"/>
			<xsd:element name="direct_supervisors" type="userAttributeType"/>
			<xsd:element name="app_approval_usg_ent_id" type="userAttributeType"/>
			<xsd:element name="supervised_groups" type="userAttributeType"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="userProfileType">
		<xsd:sequence>
			<xsd:element name="profile_attributes" type="profileAttributesType"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="accountSuspensionType">
		<xsd:attribute name="active" type="xsd:boolean" use="required"/>
		<xsd:attribute name="max_trial" type="posIntType" use="optional"/>
	</xsd:complexType>
	<xsd:complexType name="forgetPasswordType">
		<xsd:attribute name="active" type="xsd:boolean" use="required"/>
		<xsd:attribute name="link_last_days" type="xsd:int" use="required"/>
		<xsd:attribute name="max_attempt" type="xsd:int" use="required"/>
	</xsd:complexType>
	<xsd:complexType name="accountRegistrationType">
		<xsd:attribute name="active" type="xsd:boolean" use="required"/>
	</xsd:complexType>
	<xsd:element name="user_management">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="account_registration" type="accountRegistrationType"/>
				<xsd:element name="forget_password" type="forgetPasswordType"/>
				<xsd:element name="account_suspension" type="accountSuspensionType"/>
				<xsd:element name="user_profile" type="userProfileType"/>				
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== Conanjun/HK_CPDT/www/WEB-INF/config/organization/cw/user_del_management.xml
<?xml version="1.0" encoding="UTF-8"?>
<user_management xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="..\user_management.xsd">
	<!-- 
	account_registration
	Description:
		Enable/disable the account registration related functions
	Value:
		active: "true" | "false"
	Remarks:
		If it is set to active, the account registration function and the registration approval function will be enabled, and vice versa. 
	-->
	<account_registration active="true"/>	
	<!--  
	forget_password
	Description:
		Enable/disable the forget password functions
	Value:
		active: "true" | "false"
		link_last_days: 
		max_attempt: 
	Remarks:	
	-->
	<forget_password max_attempt="3" link_last_days="1" active="true"/>	
	<!-- 
	account_suspension
	Description:
		Enable/disable the account suspension related functions
	Value:
		active: "true" | "false"
		max_trial: A positive integer that determines the max number of consecutive login failure before the account is suspended.
	Remarks:
		If it is set to active, the account suspension function and reactivation function will be enabled respectively, and vice versa. 
	-->
	<account_suspension active="true" max_trial="6"/>
	<!-- 
	user_profile
	Description: Properties of user profile aTcttributes
	-->
	<user_profile>
		<!-- 
		profile_attributes
		Description:
			- Define which user attributes are hidden from or readonly to the end users.
			- Define which user extension attributes are active.
		Value:
			Attributes of the user profile, represented by the following tags:  
				<user_id/>
				<name/>
				<gender/>
				<date_of_birth/>
				<email/>
				<phone/>
				<fax/>
				<job_title/>
				<grade/>
				<group/>
				<direct_supervisors/>
				<join_date/>
				<role/>
				<extension_1/>
				<extension_2/>
				<extension_3/>
				<extension_4/>
				<extension_5/>
				<extension_6/>
				<extension_7/>
				<extension_8/>
				<extension_9/>
				<extension_10/>
				<extension_11/>
				<extension_12/>
				<extension_13/>
				<extension_14/>
				<extension_15/>
				<extension_16/>
				<extension_17/>
				<extension_18/>
				<extension_19/>
				<extension_20/>
				<extension_21/>
				<extension_22/>
				<extension_23/>
				<extension_24/>
				<extension_25/>
				<extension_26/>
				<extension_27/>
				<extension_28/>
				<extension_29/>
				<extension_30/>
				<extension_31/>
				<extension_32/>
				<extension_33/>
				<extension_34/>
				<extension_35/>
				<extension_36/>
				<extension_37/>
				<extension_38/>
				<extension_39/>
				<extension_40/>
				<supervised_groups/>
			For each of the above tag, one of the followng XML attributes may be added: 
				hidden="true": It means the attributes is hidden from the end users. 
				readonly="true": It means the user attribute is read-only to the end users. If hidden="true" is also used, this read-only property is ignored.
			For the extension attrbutes, i.e. extension_1 to extension_40, the following XML attribute MUST be defined:
				active="true" | "false": It defines if the extension attribute is used in the system or not. If active="false", both hidden="true" and readonly="true" properties are ignored. 
			For each of the above tag except <password/>, the following XML attributes may be added:
			    instr_attr="true" | "false": It defines if the field will be shown in Instructor Database.
			                                            For non-extension field, it will be shown as read-only in Instructor Database.
			                                            For extension field, it will be shown as read-only in Instructor Database its active is "true". Otherwise, it will be editable in Instructor Database.
			For each of the above tag, sub-tag of the user attribute name must be defined in each of the language used.
				The format is <label xml:lang="{language_code}">{text}</label> 
					where {language_code} follows IETF RFC 1766, 
					in which 
						en-us refers to English (United States), 
						zh-cn refers to Chinese (PRC), 
						zh-hk refers to Chinese (Hong Kong).						
		Remarks:
			- If both readonly="true" and hidden="true" are NOT defined for a user attribute, it is open for end user modification. 
			- User ID must be read-only by design.
			- Password must be hidden by design.
		-->
		<profile_attributes>
			<user_id readonly="true" searchable="all" min_length="3" max_length="20" instr_attr="true" type="text" fieldname="usr_id" publicity="0" group="personal" registration="true" allowEmpty="false">
				<label xml:lang="en-us">User ID</label>
				<label xml:lang="zh-cn">用户名</label>
				<label xml:lang="zh-hk">用戶名</label>
			</user_id>
		</profile_attributes>
		<!--
		GRADE_LIST
		Description:
			This defines the selection list used for the grade attribute. 
		Value:
			Max number of selection up to 50 (i.e. id assigned up to 50).		
		-->
		<!--		<grade_list>
			<grade id="1">Director</grade>
			<grade id="2">Associate Director</grade>
			<grade id="3">Senior Manager</grade>
			<grade id="4">Manager</grade>
			<grade id="5">Senior Associate</grade>
			<grade id="6">Associate</grade>
			<grade id="7">Unassigned</grade>
		</grade_list>-->
	</user_profile>
</user_management>
